CLASS z2mse_extr3_where_used_builder DEFINITION
  PUBLIC
  INHERITING FROM z2mse_extr3_association_build
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS search_up REDEFINITION.
    METHODS search_down REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z2MSE_EXTR3_WHERE_USED_BUILDER IMPLEMENTATION.

  METHOD search_up.

  ENDMETHOD.

  METHOD search_down.

  ENDMETHOD.

ENDCLASS.
