CLASS z2mse_test2_cl_a DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: attribute TYPE c LENGTH 1.
    METHODS method.
    METHODS method2.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z2mse_test2_cl_a IMPLEMENTATION.
  METHOD method.
  ENDMETHOD.
  METHOD method2.
    method( ).
    SELECT * INTO TABLE @DATA(s) FROM sflight.
  ENDMETHOD.

ENDCLASS.
